name = "mylean"
version = "0.1.0"
defaultTargets = ["mylean"]

[[lean_lib]]
name = "Mylean"

[[lean_exe]]
name = "mylean"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "MIL"
srcDir = "."